In [ ]:
import numpy as np
a=np.array([1,2,3]).tolist()
print(a)

[1, 2, 3]


In [ ]:
import numpy as np 
k =0
array = np.array([[1,8],[0,4]])
k=np.trace(array)
print(k)

5


In [ ]:
import numpy as np
x = np.array([[0, 5, 15], [20, 30, 40]])
print(x)
print("Values bigger than 10 =", x[x>10])



[[ 0  5 15]
 [20 30 40]]
Values bigger than 10 = [15 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


In [ ]:
import numpy as np
a = np.array([8,4,0])
b = np.array([7,9,6])
c = np.add(a,b)
print(c)

[5 7 9]


In [ ]:
import numpy as np 
from statistics import mean 
a=np.arange(8).reshape(4,2)
print(a.mean(a[0,1]))

[0.5 2.5 4.5 6.5]
